#!/bin/bash

if [ -z "$1" ] 
then
	sudo npm cache clean -f
	sudo n lts
else
	while getopts "hpur:v:" OPTION
	do
		case $OPTION in
			h)
				echo $'\e[37m' 'nup 				| install lts version of node'
				echo $'\e[37m' 'nup -v <x.x.x>			| install and use specific version'
				echo $'\e[37m' 'nup -r <x.x.x>			| remove version of node'
				echo $'\e[37m' 'nup -p				| prune all other node versions'
				echo $'\e[37m' 'nup -u				| choose node version to use'
				;;
			v)
				sudo npm cache clean -f
				sudo n $OPTARG
				;;
			r)
				sudo n rm $OPTARG
				;;
			p)
				sudo n prune
				;;
			u)
				sudo n
				;;
		esac
	done
fi